[build-system]
requires = ["setuptools>=68"]
build-backend = "setuptools.build_meta"

[project]
name = "comfyui-better-gemini"
description = "ComfyUI nodes for Google Gemini and xAI Grok image and text generation with a v3 ComfyUI node interface."
dependencies = ["google-genai>=0.5.0"]
version = "1.2.0"
requires-python = ">=3.9"
license = "MIT"
classifiers = [
    "Operating System :: OS Independent",
]


[project.urls]
Repository = "https://github.com/ttulttul/Better-Gemini"

[tool.comfy]
PublisherId = "ttulttul"
DisplayName = "ComfyUI-Better-Gemini"

[dependency-groups]
dev = []
